#!/bin/bash

# ECS 컨테이너 메타데이터에서 IP 추출
export EUREKA_INSTANCE_HOSTNAME=$(curl -s $ECS_CONTAINER_METADATA_URI_V4 | jq -r '.Networks[0].IPv4Addresses[0]')

# Spring Boot 실행
java -jar \
  -DEUREKA_INSTANCE_HOSTNAME=$EUREKA_INSTANCE_HOSTNAME \
  -DDB_URL=${ENV_DB_URL} \
  -DDB_USERNAME=${ENV_DB_USERNAME} \
  -DDB_PASSWORD=${ENV_DB_PASSWORD} \
  -DDB_DDL_AUTO=${ENV_DB_DDL_AUTO} \
  -DJWT_SECRET=${ENV_JWT_SECRET} \
  -DACCESS_TOKEN_EXPIRATION=${ENV_ACCESS_TOKEN_EXPIRATION} \
  -DREFRESH_TOKEN_EXPIRATION=${ENV_REFRESH_TOKEN_EXPIRATION} \
  app.jar

